spring:
    profiles.active: local
    application.name: AlegorFlix
    banner.location: static/banner.txt
    data.mongodb:
      uri: ${MONGOURI:mongodb://localhost/alegorflix}
      port: 27017
      username:
      password:

